yarnPath: .yarn/releases/yarn-4.3.0.cjs

# Cache settings
cacheFolder: .yarn/cache
enableGlobalCache: true

# Checksum behavior
checksumBehavior: update

# Node linker
nodeLinker: node-modules

# Registry settings
npmRegistryServer: "https://registry.yarnpkg.com"

# Hoisting limits
nmHoistingLimits: workspaces

# Enable colors in output
enableColors: true

# Enable constraints checks
enableConstraintsChecks: true

# Enable hardened mode for security
enableHardenedMode: true

# Enable hyperlinks in output
enableHyperlinks: true

# Enable immutable cache
enableImmutableCache: false

# Enable immutable installs
enableImmutableInstalls: false
