name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          check-latest: true
      - name: Set Yarn version
        run: corepack prepare yarn@4.3.1 --activate
      - name: Get Yarn cache directory
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
        id: yarn-cache-dir
      - name: Get Yarn version
        run: echo "YARN_VERSION=$(yarn --version)" >> $GITHUB_ENV
        id: yarn-version
      - name: Print Yarn version
        run: yarn --version
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-yarn-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Save yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-yarn-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-yarn-${{ env.YARN_VERSION }}-
            yarn-cache-${{ runner.os }}-yarn-
            yarn-cache-
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn lint:changelog
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty after building"
            exit 1
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-lint-test
    steps:
      - run: echo "Great success!"
