name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Set Yarn version to 4.3.0
        run: yarn set version 4.3.0
      - name: Get Yarn cache directory
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV
        id: yarn-cache-dir
      - name: Get Yarn version
        run: echo "YARN_VERSION=$(yarn --version)" >> $GITHUB_ENV
        id: yarn-version
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-${{ steps.yarn-version.outputs.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn allow-scripts
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      # Triggering a new run
      - name: Trigger new run
        run: echo "Triggering a new run to ensure latest changes are applied"
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-lint-test
    steps:
      - run: echo "Great success!"
