name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set Yarn version to 4.3.0
        run: corepack prepare yarn@4.3.0 --activate
      - name: Get Yarn cache directory
        run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV
        id: yarn-cache-dir
      - name: Get Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          echo "YARN_VERSION=$(yarn --version)" >> $GITHUB_ENV
        id: yarn-version
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-${{ env.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
      - name: Print Yarn configuration
        run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn config list
      - run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn install --immutable
      - run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn allow-scripts
      - run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn build
      - run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn lint
      - run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn test
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn auto-changelog validate --rc
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: |
          corepack enable
          corepack prepare yarn@4.3.0 --activate
          yarn auto-changelog validate
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty after building"
            exit 1
          fi
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-20.04
    needs:
      - build-lint-test
    steps:
      - run: echo "Great success!"
